### ISSUE TITLE
Throttle hits to the Scryfall API

### ISSUE THREAD

**Issue by phrazzld** [phrazzld/kitchen-table-magic#3]
Don't wanna get rate limited; or worse, IP-banned.

We should have a local database with each card we've used, and search our database for matches before reaching out to Scryfall.

**Comment by moomooskycow** [comment]
Done, handled with `lodash.debounce`.

Really, we should be doing something fancier, like storing a lot of this in our own database and checking there before querying Scryfall, something something caching, etc -- but for now, this'll do
